import { useParams, useNavigate } from 'react-router'
import { motion, AnimatePresence } from 'motion/react'
import { ArrowLeft, Heart, Share2, Play, User, Target, AlertCircle, Zap, Music, TrendingUp, ChevronDown, ChevronUp, Palette, Tag, BookOpen, Users as UsersIcon } from 'lucide-react'
import { useMemo, useState } from 'react'
import { characterCards, getCharacterBySlug, getCreatorBySlug, getSongBySlug, getWorkBySlug, mapCharacterToDetail } from '../data/adapters'
import { usePlayer } from '../context/PlayerContext'

export function CharacterDetail() {
  const { slug } = useParams()
  const navigate = useNavigate()
  const { playTrack } = usePlayer()
  const [isLiked, setIsLiked] = useState(false)
  const [lyricsExpanded, setLyricsExpanded] = useState(false)

  const rawCharacter = slug ? getCharacterBySlug(slug) : undefined
  const character = rawCharacter ? mapCharacterToDetail(rawCharacter) : undefined
  const song = rawCharacter?.songSlugs?.[0] ? getSongBySlug(rawCharacter.songSlugs[0]) : undefined
  const work = rawCharacter?.workSlugs?.[0] ? getWorkBySlug(rawCharacter.workSlugs[0]) : undefined

  const similarCards = useMemo(() => {
    if (!rawCharacter) return []
    const slugs = new Set(rawCharacter.similarCharacterSlugs)
    return characterCards.filter((item) => slugs.has(item.slug)).slice(0, 4)
  }, [rawCharacter])

  if (!rawCharacter || !character) return <div className="min-h-full flex items-center justify-center" style={{ color: '#6C7A89' }}>人物未找到</div>
  const primaryCreatorName = rawCharacter.creatorSlugs.map((item) => getCreatorBySlug(item)?.name).filter(Boolean).join('、')
  const coreUnderstanding = [
    { title: '他是谁', content: character.identity, icon: User, gradient: 'linear-gradient(135deg, rgba(214, 179, 106, 0.15) 0%, rgba(108, 122, 137, 0.05) 100%)' },
    { title: '他在追什么', content: character.desire, icon: Target, gradient: 'linear-gradient(135deg, rgba(108, 122, 137, 0.15) 0%, rgba(214, 179, 106, 0.05) 100%)' },
    { title: '他最怕什么', content: character.fear, icon: AlertCircle, gradient: 'linear-gradient(135deg, rgba(214, 179, 106, 0.12) 0%, rgba(108, 122, 137, 0.08) 100%)' },
    { title: '他的矛盾', content: character.conflict, icon: Zap, gradient: 'linear-gradient(135deg, rgba(108, 122, 137, 0.12) 0%, rgba(214, 179, 106, 0.08) 100%)' }
  ]
  const relationCards = [
    { title: '对爱情', value: character.relationships.love },
    { title: '对权威', value: character.relationships.authority },
    { title: '对朋友', value: character.relationships.friends },
    { title: '对敌人', value: character.relationships.enemies },
  ].filter((item) => item.value)

  return <div className="min-h-full pb-6">
    <div className="relative overflow-hidden" style={{ height: '60vh' }}>
      <motion.img initial={{ scale: 1.08 }} animate={{ scale: 1 }} transition={{ duration: 1.2, ease: 'easeOut' }} src={character.imageUrl} alt={character.name} className="w-full h-full object-cover" />
      <div className="absolute inset-0" style={{ background: 'linear-gradient(to top, rgba(15,17,21,0.96) 0%, rgba(15,17,21,0.75) 40%, rgba(15,17,21,0.3) 70%, transparent 100%)' }} />
      <motion.button initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.5 }} onClick={() => navigate(-1)} className="absolute top-6 left-5 w-10 h-10 rounded-full flex items-center justify-center backdrop-blur-sm" style={{ background: 'rgba(26,29,35,0.6)' }}><ArrowLeft size={20} style={{ color: '#FFFFFF' }} /></motion.button>
      <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.5 }} className="absolute top-6 right-5 flex gap-2"><button onClick={() => setIsLiked(!isLiked)} className="w-10 h-10 rounded-full flex items-center justify-center backdrop-blur-sm" style={{ background: 'rgba(26,29,35,0.6)' }}><Heart size={20} fill={isLiked ? '#D6B36A' : 'none'} style={{ color: isLiked ? '#D6B36A' : '#FFFFFF' }} /></button><button className="w-10 h-10 rounded-full flex items-center justify-center backdrop-blur-sm" style={{ background: 'rgba(26,29,35,0.6)' }}><Share2 size={20} style={{ color: '#FFFFFF' }} /></button></motion.div>
      <div className="absolute bottom-0 left-0 right-0 px-5 pb-8"><motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7, delay: 0.15 }}><div className="inline-flex items-center gap-2 mb-3 rounded-full px-3 py-1 text-xs" style={{ background: 'rgba(214,179,106,0.12)', color: '#D6B36A' }}>{work?.title} · {character.title.split(' · ')[1]}</div><h1 className="text-4xl mb-2" style={{ color: '#FFFFFF', textShadow: '0 2px 20px rgba(0,0,0,0.5)' }}>{character.name}</h1><p className="text-base leading-relaxed mb-5" style={{ color: '#E7ECF2' }}>{character.quote}</p><div className="flex flex-wrap gap-2 mb-5">{character.tags.map((tag)=><span key={tag} className="px-3 py-1.5 rounded-full text-xs backdrop-blur-sm" style={{ background: 'rgba(26,29,35,0.7)', color: '#D6B36A', border: '1px solid rgba(214,179,106,0.3)' }}>{tag}</span>)}</div><div className="flex gap-3">{song && <button className="flex items-center gap-2 px-5 py-3 rounded-full" style={{ background: '#D6B36A', color: '#0F1115' }} onClick={() => playTrack({ title: song.title, subtitle: character.name, coverUrl: song.coverUrl, audioUrl: song.audioUrl })}><Play size={16} fill="#0F1115" /> 播放人物之歌</button>}<button className="px-5 py-3 rounded-full" style={{ background: 'rgba(255,255,255,0.08)', color: '#FFFFFF' }} onClick={() => song && playTrack({ title: song.title, subtitle: character.name, coverUrl: song.coverUrl, audioUrl: song.audioUrl })}>歌曲列表</button></div></motion.div></div>
    </div>
    <div className="px-5 py-6">
      <section className="mb-8"><div className="flex items-center gap-2 mb-4"><TrendingUp size={18} style={{ color: '#D6B36A' }} /><h2 style={{ color: '#FFFFFF' }}>核心理解</h2></div><div className="grid grid-cols-2 gap-3">{coreUnderstanding.map((item,index)=>{const Icon=item.icon; return <motion.div key={item.title} initial={{ opacity:0, y:20 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.45, delay:0.25+index*0.06 }} className="rounded-2xl p-4" style={{ background:item.gradient, border:'1px solid rgba(255,255,255,0.04)' }}><div className="flex items-center gap-2 mb-3"><Icon size={16} style={{ color:'#D6B36A' }} /><span className="text-xs" style={{ color:'#D6B36A' }}>{item.title}</span></div><p className="text-sm leading-relaxed" style={{ color:'#E7ECF2' }}>{item.content}</p></motion.div>})}</div></section>
      <section className="mb-8"><div className="flex items-center gap-2 mb-4"><Tag size={18} style={{ color: '#D6B36A' }} /><h2 style={{ color: '#FFFFFF' }}>性格与情绪</h2></div><div className="space-y-3">{[{ title: '表面是什么样的人', tags: rawCharacter.surfaceTraits, description: character.description },{ title: '心里真正卡住的是什么', tags: rawCharacter.deepTraits, description: character.psychology },{ title: '他长期活在什么情绪里', tags: rawCharacter.dominantEmotions, description: character.emotionalStructure },{ title: '他最看重什么', tags: rawCharacter.valuesTags, description: `他不会轻易放弃这些东西：${rawCharacter.valuesTags.join('、')}` }].map((section)=><div key={section.title} className="rounded-2xl p-4" style={{ background:'#1A1D23' }}><div className="text-sm mb-3" style={{ color:'#FFFFFF' }}>{section.title}</div><div className="flex flex-wrap gap-2 mb-3">{section.tags.map((tag)=><span key={tag} className="px-3 py-1 rounded-full text-xs" style={{ background:'rgba(108,122,137,0.15)', color:'#ADB7C2' }}>{tag}</span>)}</div><p className="text-sm leading-relaxed" style={{ color:'#6C7A89' }}>{section.description}</p></div>)}</div></section>
      <section className="mb-8"><div className="flex items-center gap-2 mb-4"><TrendingUp size={18} style={{ color: '#D6B36A' }} /><h2 style={{ color: '#FFFFFF' }}>命运轨迹</h2></div><div className="rounded-2xl p-5" style={{ background:'#1A1D23' }}><div className="space-y-6">{character.timeline.map((item,index)=><div key={item.year} className="relative pl-7"><div className="absolute left-0 top-1.5 w-3 h-3 rounded-full" style={{ background:'#D6B36A' }} />{index<character.timeline.length-1 && <div className="absolute left-[5px] top-5 w-px h-[54px]" style={{ background:'rgba(214,179,106,0.2)' }} /> }<div className="text-xs mb-1" style={{ color:'#D6B36A' }}>阶段 {item.year}</div><h4 className="mb-1" style={{ color:'#FFFFFF' }}>{item.event}</h4><p className="text-sm leading-relaxed" style={{ color:'#6C7A89' }}>{item.emotion}</p></div>)}</div><div className="mt-6 rounded-xl p-4" style={{ background:'rgba(214,179,106,0.08)' }}><div className="text-xs mb-2" style={{ color:'#D6B36A' }}>结尾状态</div><div className="text-sm leading-relaxed" style={{ color:'#E7ECF2' }}>{rawCharacter.endingState}</div></div></div></section>
      <section className="mb-8"><div className="flex items-center gap-2 mb-4"><UsersIcon size={18} style={{ color: '#D6B36A' }} /><h2 style={{ color: '#FFFFFF' }}>关系模式</h2></div><div className="flex gap-3 overflow-x-auto pb-2" style={{ scrollbarWidth: 'none' }}>{relationCards.map((item)=><div key={item.title} className="flex-shrink-0 w-[260px] rounded-2xl p-4" style={{ background:'#1A1D23' }}><div className="text-sm mb-2" style={{ color:'#FFFFFF' }}>{item.title}</div><p className="text-sm leading-relaxed" style={{ color:'#6C7A89' }}>{item.value}</p></div>)}</div></section>
      <section className="mb-8"><div className="flex items-center gap-2 mb-4"><Palette size={18} style={{ color: '#D6B36A' }} /><h2 style={{ color: '#FFFFFF' }}>象征意象</h2></div><div className="rounded-2xl p-5" style={{ background:'#1A1D23' }}><div className="mb-5"><div className="text-xs mb-3" style={{ color:'#6C7A89' }}>颜色</div><div className="flex gap-3">{rawCharacter.colors.map((color)=><div key={color.name} className="text-center"><div className="w-10 h-10 rounded-full border mb-2" style={{ background:color.hex, borderColor:'rgba(255,255,255,0.08)' }} /><div className="text-[11px]" style={{ color:'#ADB7C2' }}>{color.name}</div></div>)}</div></div><div className="space-y-4"><div><div className="text-xs mb-2" style={{ color:'#6C7A89' }}>意象</div><div className="flex flex-wrap gap-2">{rawCharacter.symbolicImages.map((item)=><span key={item} className="px-3 py-1 rounded-full text-xs" style={{ background:'rgba(108,122,137,0.15)', color:'#ADB7C2' }}>{item}</span>)}</div></div><div><div className="text-xs mb-2" style={{ color:'#6C7A89' }}>声音</div><div className="flex flex-wrap gap-2">{rawCharacter.soundscapeKeywords.map((item)=><span key={item} className="px-3 py-1 rounded-full text-xs" style={{ background:'rgba(108,122,137,0.15)', color:'#ADB7C2' }}>{item}</span>)}</div></div></div></div></section>
      {song && <section className="mb-8"><div className="flex items-center gap-2 mb-4"><Music size={18} style={{ color: '#D6B36A' }} /><h2 style={{ color: '#FFFFFF' }}>人物之歌</h2></div><div className="rounded-2xl overflow-hidden" style={{ background:'#1A1D23' }}><div className="relative h-56 overflow-hidden"><img src={song.coverUrl} alt={song.title} className="w-full h-full object-cover" /><div className="absolute inset-0" style={{ background:'linear-gradient(to top, rgba(26,29,35,0.96) 0%, rgba(26,29,35,0.25) 100%)' }} /><div className="absolute bottom-0 left-0 right-0 p-5 flex items-end justify-between gap-4"><div><div className="text-xs mb-1" style={{ color:'#D6B36A' }}>{primaryCreatorName}</div><h3 className="text-xl mb-2" style={{ color:'#FFFFFF' }}>{song.title}</h3><p className="text-sm leading-relaxed" style={{ color:'#E7ECF2' }}>{song.songCoreTheme}</p></div><button className="w-14 h-14 rounded-full flex items-center justify-center" style={{ background:'#D6B36A', color:'#0F1115' }} onClick={() => playTrack({ title: song.title, subtitle: character.name, coverUrl: song.coverUrl, audioUrl: song.audioUrl })}><Play size={18} fill="#0F1115" /></button></div></div><div className="p-5 space-y-4"><div className="rounded-xl p-4" style={{ background:'rgba(15,17,21,0.45)' }}><div className="text-xs mb-2" style={{ color:'#6C7A89' }}>情绪曲线</div><div className="text-sm" style={{ color:'#E7ECF2' }}>{song.emotionalCurve.join(' → ')}</div></div><div className="rounded-xl p-4" style={{ background:'rgba(15,17,21,0.45)' }}><div className="text-xs mb-2" style={{ color:'#6C7A89' }}>风格</div><div className="text-sm" style={{ color:'#E7ECF2' }}>{song.songStyles.join(' / ')}</div></div><div className="rounded-xl p-4" style={{ background:'rgba(15,17,21,0.45)' }}><div className="text-xs mb-2" style={{ color:'#6C7A89' }}>音色</div><div className="text-sm" style={{ color:'#E7ECF2' }}>{song.vocalProfile}</div></div><div className="rounded-xl p-4" style={{ background:'rgba(15,17,21,0.45)' }}><button className="w-full flex items-center justify-between" onClick={() => setLyricsExpanded(!lyricsExpanded)}><span className="text-sm" style={{ color:'#FFFFFF' }}>歌词片段</span>{lyricsExpanded ? <ChevronUp size={16} style={{ color:'#6C7A89' }} /> : <ChevronDown size={16} style={{ color:'#6C7A89' }} />}</button><AnimatePresence>{lyricsExpanded && <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }} className="overflow-hidden"><div className="mt-3 pt-3 border-t" style={{ borderColor: 'rgba(108,122,137,0.15)' }}>{character.lyrics.map((line, idx) => <p key={idx} className="text-sm leading-relaxed mb-2" style={{ color:'#6C7A89' }}>{line}</p>)}</div></motion.div>}</AnimatePresence></div></div></div></section>}
      <section><div className="flex items-center gap-2 mb-4"><BookOpen size={18} style={{ color: '#D6B36A' }} /><h2 style={{ color: '#FFFFFF' }}>继续探索</h2></div><div className="space-y-3 mb-4">{work && <div className="rounded-2xl p-4 cursor-pointer" style={{ background:'#1A1D23' }} onClick={() => navigate(`/work/${work.slug}`)}><div className="text-xs mb-1" style={{ color:'#6C7A89' }}>所属作品</div><div style={{ color:'#FFFFFF' }}>{work.title}</div></div>}<div className="rounded-2xl p-4 cursor-pointer" style={{ background:'#1A1D23' }} onClick={() => rawCharacter.creatorSlugs[0] && navigate(`/creator/${rawCharacter.creatorSlugs[0]}`)}><div className="text-xs mb-1" style={{ color:'#6C7A89' }}>创作者</div><div style={{ color:'#FFFFFF' }}>{primaryCreatorName}</div></div></div><div className="flex gap-3 overflow-x-auto pb-2" style={{ scrollbarWidth: 'none' }}>{similarCards.map((item)=><button key={item.id} className="flex-shrink-0 w-40 rounded-2xl overflow-hidden text-left" style={{ background:'#1A1D23' }} onClick={() => navigate(`/character/${item.slug}`)}><div className="h-28 overflow-hidden"><img src={item.imageUrl} alt={item.name} className="w-full h-full object-cover" /></div><div className="p-3"><div className="text-sm mb-1" style={{ color:'#FFFFFF' }}>{item.name}</div><div className="text-xs line-clamp-2" style={{ color:'#6C7A89' }}>{item.description}</div></div></button>)}</div></section>
    </div>
  </div>
}
